# Generated by Django 4.2.5 on 2023-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_certificaterequest_issuing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(default='2003-05-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(),
        ),
    ]
