# Generated by Django 4.2.5 on 2023-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_alter_enrollment_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='issuing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(),
        ),
    ]
