# Generated by Django 4.2.5 on 2023-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0005_certificaterequest_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='issuing_authority',
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='issuing_authority',
            field=models.CharField(default='3hh73', max_length=100),
            preserve_default=False,
        ),
    ]
