# Generated by Django 4.2.5 on 2023-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0006_remove_certification_issuing_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
