# Generated by Django 4.2.5 on 2023-09-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0007_certificaterequest_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='certificate_file',
        ),
    ]
